#include "images.h"

const ext_img_desc_t images[29] = {
    { "Avatar", &img_avatar },
    { "Avatar1", &img_avatar1 },
    { "arrow_forward", &img_arrow_forward },
    { "arrow_forward1", &img_arrow_forward1 },
    { "chevron_left", &img_chevron_left },
    { "chevron_right", &img_chevron_right },
    { "ecg_heart", &img_ecg_heart },
    { "history", &img_history },
    { "person", &img_person },
    { "red_body", &img_red_body },
    { "syringe", &img_syringe },
    { "hold_sensor", &img_hold_sensor },
    { "ecg_heart_1", &img_ecg_heart_1 },
    { "spo2_1", &img_spo2_1 },
    { "glucose_1", &img_glucose_1 },
    { "blood_pressure_1", &img_blood_pressure_1 },
    { "ryg4040", &img_ryg4040 },
    { "check", &img_check },
    { "check1", &img_check1 },
    { "measuring", &img_measuring },
    { "favorite", &img_favorite },
    { "favorite_dis", &img_favorite_dis },
    { "favorite_en", &img_favorite_en },
    { "humidity_high_dis", &img_humidity_high_dis },
    { "humidity_high_en", &img_humidity_high_en },
    { "nest_secure_alarm_dis", &img_nest_secure_alarm_dis },
    { "nest_secure_alarm_en", &img_nest_secure_alarm_en },
    { "total_dissolved_solids_dis", &img_total_dissolved_solids_dis },
    { "total_dissolved_solids_en", &img_total_dissolved_solids_en },
};
