#include "images.h"

const ext_img_desc_t images[44] = {
    { "Avatar", &img_avatar },
    { "Avatar1", &img_avatar1 },
    { "arrow_forward", &img_arrow_forward },
    { "arrow_forward1", &img_arrow_forward1 },
    { "chevron_left", &img_chevron_left },
    { "chevron_right", &img_chevron_right },
    { "ecg_heart", &img_ecg_heart },
    { "history", &img_history },
    { "person", &img_person },
    { "red_body", &img_red_body },
    { "syringe", &img_syringe },
    { "hold_sensor", &img_hold_sensor },
    { "ecg_heart_1", &img_ecg_heart_1 },
    { "spo2_1", &img_spo2_1 },
    { "glucose_1", &img_glucose_1 },
    { "blood_pressure_1", &img_blood_pressure_1 },
    { "ryg4040", &img_ryg4040 },
    { "check", &img_check },
    { "check1", &img_check1 },
    { "measuring", &img_measuring },
    { "favorite", &img_favorite },
    { "favorite_dis", &img_favorite_dis },
    { "favorite_en", &img_favorite_en },
    { "humidity_high_dis", &img_humidity_high_dis },
    { "humidity_high_en", &img_humidity_high_en },
    { "nest_secure_alarm_dis", &img_nest_secure_alarm_dis },
    { "nest_secure_alarm_en", &img_nest_secure_alarm_en },
    { "total_dissolved_solids_dis", &img_total_dissolved_solids_dis },
    { "total_dissolved_solids_en", &img_total_dissolved_solids_en },
    { "eject", &img_eject },
    { "pf1", &img_pf1 },
    { "pf2", &img_pf2 },
    { "pf3", &img_pf3 },
    { "pf4", &img_pf4 },
    { "pf5", &img_pf5 },
    { "pf6", &img_pf6 },
    { "pf7", &img_pf7 },
    { "pf8", &img_pf8 },
    { "pf9", &img_pf9 },
    { "pf10", &img_pf10 },
    { "check_green", &img_check_green },
    { "insert_pod", &img_insert_pod },
    { "inject_insert", &img_inject_insert },
    { "monitor_prepare", &img_monitor_prepare },
};
